import firebase from 'firebase';

const charNames = [
  'breach',
  'brimstone',
  'cypher',
  'jett',
  'killjoy',
  'omen',
  'phoenix',
  'raze',
  'reyna',
  'sage',
  'skye',
  'sova',
  'viper',
  'yoru',
];

function loadDB() {
  var i;
  for (i in charNames) {
    console.log(i);
    firebase
      .database()
      .ref('valorant/characters/' + charNames[i])
      .set({
        charCount: 0,
        gunCount: {
          classic: 0,
          fenzy: 0,
          shorty: 0,
          ghost: 0,
          sherrif: 0,
          stinger: 0,
          spectre: 0,
          bucky: 0,
          judge: 0,
          bulldog: 0,
          guardian: 0,
          phantom: 0,
          vandal: 0,
          marshal: 0,
          operator: 0,
          ares: 0,
          odin: 0,
        },
        round: {
          one: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
          two: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
          three: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
          four: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
          five: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
          six: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
          seven: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
          eight: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
          nine: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
          ten: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
          eleven: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
          twelve: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
          thirteen: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
          fourteen: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
          fifteen: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
          sixteen: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
          seventeen: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
          eighteen: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
          nineteen: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
          twenty: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
          twentyone: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
          twentytwo: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
          twentythree: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
          overtime: {
            classic: { count: 0, win: 0, loss: 0 },
            frenzy: { count: 0, win: 0, loss: 0 },
            shorty: { count: 0, win: 0, loss: 0 },
            ghost: { count: 0, win: 0, loss: 0 },
            sherrif: { count: 0, win: 0, loss: 0 },
            stinger: { count: 0, win: 0, loss: 0 },
            spectre: { count: 0, win: 0, loss: 0 },
            bucky: { count: 0, win: 0, loss: 0 },
            judge: { count: 0, win: 0, loss: 0 },
            bulldog: { count: 0, win: 0, loss: 0 },
            guardian: { count: 0, win: 0, loss: 0 },
            phantom: { count: 0, win: 0, loss: 0 },
            vandal: { count: 0, win: 0, loss: 0 },
            marshal: { count: 0, win: 0, loss: 0 },
            operator: { count: 0, win: 0, loss: 0 },
            ares: { count: 0, win: 0, loss: 0 },
            odin: { count: 0, win: 0, loss: 0 },
          },
        },
      });
  }

  firebase.database().ref('valorant/guns').set({
    classic: 0,
    frenzy: 0,
    shorty: 0,
    ghost: 0,
    sherrif: 0,
    stinger: 0,
    spectre: 0,
    bucky: 0,
    judge: 0,
    bulldog: 0,
    guardian: 0,
    phantom: 0,
    vandal: 0,
    marshal: 0,
    operator: 0,
    ares: 0,
    odin: 0,
  });
}

export default loadDB;
